# Generated by Django 4.1.6 on 2023-02-02 09:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Localisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Wilaya', models.CharField(max_length=50)),
                ('Commune', models.CharField(max_length=50)),
                ('zip', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_Annonce', models.CharField(max_length=300)),
                ('surface_Annonce', models.IntegerField(null=True)),
                ('description_Annonce', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('prix_Annonce', models.FloatField(null=True)),
                ('date_Annonce', models.DateTimeField(default=django.utils.timezone.now)),
                ('images_Annonce', models.ImageField(upload_to='uploads/')),
                ('category_Annonce', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.category')),
                ('localisation_Annonce', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.localisation')),
                ('type_Annonce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.type')),
            ],
        ),
    ]
