# Generated by Django 4.1.6 on 2023-02-02 17:24

import core.models.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_rename_commune_localisation_commune_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annonce',
            name='images_Annonce',
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=core.models.models.get_image_filename, verbose_name='Image')),
                ('annonce_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.annonce')),
            ],
        ),
    ]
