# Generated by Django 4.1.6 on 2023-02-03 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_offre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offre',
            name='id_sender',
        ),
    ]
