# Generated by Django 4.1.5 on 2023-02-01 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_Annonce', models.CharField(max_length=300)),
                ('categorie_Annonce', models.CharField(choices=[], default='LOCATION', max_length=100)),
                ('type_Annonce', models.CharField(max_length=50)),
                ('surface_Annonce', models.IntegerField(null=True)),
                ('description_Annonce', models.TextField()),
                ('prix_Annonce', models.FloatField(null=True)),
                ('date_Annonce', models.DateTimeField(default=django.utils.timezone.now)),
                ('localisation_Annonce', models.CharField(choices=[], default='Alger', max_length=100)),
                ('images_Annonce', models.FilePathField(path='/img')),
                ('user_Annonce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
